export const COMPANY_INFO = {
  name: "Reliable Home Service",
  phone: "+91 97111 07248",
  whatsapp: "919711107248",
  email: "info@reliablehomeservice.in",
  address: "Gurugram, Haryana, India",
  workingHours: "9:00 AM - 8:00 PM",
  workingDays: "Monday - Sunday",
  experience: "10",
  servicesCompleted: "5000+",
  happyCustomers: "4500+",
};

export const SERVICES = [
  {
    id: "washing-machine-repair",
    name: "Washing Machine Repair",
    shortName: "Washing Machine",
    description: "Complete washing machine repair for top-load, front-load, and fully automatic models.",
    image: "/images/service-washing-machine.png",
    commonIssues: [
      "Machine not spinning",
      "Water not draining",
      "Drum making noise",
      "Machine vibrating excessively",
      "Water leakage",
      "Door not locking",
    ],
    brands: ["Samsung", "LG", "IFB", "Whirlpool", "Bosch", "Haier", "Godrej", "Panasonic"],
  },
  {
    id: "refrigerator-repair",
    name: "Refrigerator Repair & Service",
    shortName: "Refrigerator",
    description: "Fast and reliable fridge repair for single-door, double-door, and side-by-side models.",
    image: "/images/service-refrigerator.png",
    commonIssues: [
      "Fridge not cooling",
      "Freezer not working",
      "Water leakage inside",
      "Strange noises",
      "Ice buildup",
      "Thermostat issues",
    ],
    brands: ["Samsung", "LG", "Whirlpool", "Godrej", "Haier", "Bosch", "Panasonic", "Hitachi"],
  },
  {
    id: "microwave-repair",
    name: "Microwave Repair & Service",
    shortName: "Microwave",
    description: "Expert microwave oven repair. Fix heating, turntable, and control panel issues.",
    image: "/images/service-microwave.png",
    commonIssues: [
      "Not heating food",
      "Turntable not rotating",
      "Sparks inside",
      "Control panel not working",
      "Door not closing properly",
      "Strange smell while cooking",
    ],
    brands: ["Samsung", "LG", "IFB", "Whirlpool", "Panasonic", "Godrej", "Bajaj", "Morphy Richards"],
  },
  {
    id: "dryer-repair",
    name: "Dryer Repair & Service",
    shortName: "Dryer",
    description: "Professional clothes dryer repair services. Fix heating, tumbling, and venting issues quickly.",
    image: "/images/service-dryer.png",
    commonIssues: [
      "Dryer not heating",
      "Drum not spinning",
      "Takes too long to dry",
      "Making unusual noises",
      "Dryer overheating",
      "Not starting",
    ],
    brands: ["Samsung", "LG", "IFB", "Whirlpool", "Bosch", "Siemens", "Electrolux", "Haier"],
  },
  {
    id: "dishwasher-repair",
    name: "Dishwasher Repair & Service",
    shortName: "Dishwasher",
    description: "Expert dishwasher repair for all brands. Fix cleaning, drainage, and cycle issues.",
    image: "/images/service-dishwasher.png",
    commonIssues: [
      "Dishes not cleaning properly",
      "Water not draining",
      "Dishwasher not starting",
      "Water leakage",
      "Strange odors",
      "Spray arm not rotating",
    ],
    brands: ["Samsung", "LG", "IFB", "Bosch", "Siemens", "Whirlpool", "Faber", "Elica"],
  },
];

export const SERVICE_AREAS = [
  "DLF Phase 1-5",
  "Sector 14",
  "Sector 15",
  "Sector 17",
  "Sector 22",
  "Sector 23",
  "Sector 29",
  "Sector 31",
  "Sector 38",
  "Sector 40",
  "Sector 43",
  "Sector 45",
  "Sector 46",
  "Sector 47",
  "Sector 48",
  "Sector 49",
  "Sector 50",
  "Sector 51",
  "Sector 52",
  "Sector 53",
  "Sector 54",
  "Sector 55",
  "Sector 56",
  "Sector 57",
  "Golf Course Road",
  "Golf Course Extension",
  "Sohna Road",
  "MG Road",
  "HUDA City Centre",
  "Cyber City",
  "Udyog Vihar",
  "Palam Vihar",
  "Sushant Lok",
  "South City",
  "Nirvana Country",
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Priya Sharma",
    location: "Sector 56, Gurugram",
    rating: 5,
    service: "Washing Machine Repair",
    comment: "My washing machine was making loud noises. They diagnosed the issue and fixed it the same day. Highly recommended!",
  },
  {
    id: 2,
    name: "Neha Gupta",
    location: "Sohna Road, Gurugram",
    rating: 5,
    service: "Refrigerator Repair",
    comment: "Fast response and quality repair work. My fridge is working like new. Will definitely use their service again.",
  },
  {
    id: 3,
    name: "Rajesh Kumar",
    location: "DLF Phase 3, Gurugram",
    rating: 5,
    service: "Dishwasher Repair",
    comment: "Excellent service! The technician arrived within 2 hours and fixed my dishwasher quickly. Very professional and reasonable pricing.",
  },
  {
    id: 4,
    name: "Amit Verma",
    location: "Golf Course Road, Gurugram",
    rating: 5,
    service: "Dryer Repair",
    comment: "My dryer wasn't heating properly. The technician was knowledgeable and repaired it perfectly. Great experience!",
  },
];

export const FAQ_DATA = [
  {
    question: "What areas in Gurugram do you serve?",
    answer: "We provide doorstep home appliance repair services across all of Gurugram including DLF Phases, Sectors 14-57, Golf Course Road, Sohna Road, MG Road, Cyber City, Palam Vihar, Sushant Lok, and surrounding areas.",
  },
  {
    question: "How quickly can you provide service?",
    answer: "We offer same-day service for most repairs. Once you book, our technician will reach your doorstep within 2-4 hours depending on your location in Gurugram.",
  },
  {
    question: "What brands do you repair?",
    answer: "We repair all major brands including Samsung, LG, Whirlpool, Godrej, IFB, Bosch, Siemens, Panasonic, Haier, Electrolux, and many more.",
  },
  {
    question: "Do you provide warranty on repairs?",
    answer: "Yes, we provide 30-90 days warranty on all our repair services depending on the type of repair. Any genuine parts replaced also come with warranty.",
  },
  {
    question: "What are your service charges?",
    answer: "We provide transparent and competitive pricing. The cost depends on the type of repair needed. We always provide an upfront quote before starting any work - no hidden charges.",
  },
  {
    question: "Do you use genuine spare parts?",
    answer: "Yes, we use only genuine and high-quality spare parts for all repairs to ensure long-lasting performance of your appliances.",
  },
];

export const BRANDS = [
  "Samsung",
  "LG",
  "Whirlpool",
  "Godrej",
  "IFB",
  "Bosch",
  "Siemens",
  "Panasonic",
  "Haier",
  "Electrolux",
  "Faber",
  "Elica",
  "Bajaj",
  "Morphy Richards",
];
